version: '3.5'

networks:
   skynet:

volumes:
   logs: {}

services:

   splunk:
      image: splunk/splunk
      container_name: splunk
      environment:
         SPLUNK_START_ARGS: "--accept-license"
         SPLUNK_PASSWORD: $SPLUNK_PASSWORD
         SPLUNK_HEC_TOKEN: $SPLUNK_HEC_TOKEN
         SPLUNK_DEFAULTS_URL: $SPLUNK_DEFAULTS_URL
      ports:
         - 8000:8000
         - 8088:8088
      networks:
         - skynet

   # elasticsearch:
   #    build:
   #       context: elasticsearch/
   #    container_name: elasticsearch
   #    volumes:
   #       - elasticsearch_data:/usr/share/elasticsearch/data
   #    restart: unless-stopped
   #    environment:
   #       ES_JAVA_OPTS: "-Xmx256m -Xms256m"
   #    ports:
   #       - 9200:9200
   #       - 9300:9300
   #    networks:
   #       - logging

   # kibana:
   #    build:
   #       context: kibana/
   #    container_name: kibana
   #    restart: unless-stopped
   #    ports:
   #       - 5601:5601
   #    networks:
   #       - logging
   #    depends_on:
   #       - elasticsearch
         
   test:
      build:
         context: test-service/
      container_name: test
      ports:
         - 5001:5001
      volumes:
         - logs:/var/log
      networks:
         - skynet

   otel:
      build:
         context: otel/
      container_name: otel
      restart: always
      environment:
         SPLUNK_HEC_URL: $SPLUNK_HEC_URL
         SPLUNK_HEC_TOKEN: $SPLUNK_HEC_TOKEN
      ports:
         - 4317:4317
      volumes:
         - logs:/var/log
      networks:
         - skynet
      depends_on:
         - test