version: '3.5'

networks:
   skynet:

services:

   splunk:
      image: splunk/splunk
      environment:
         SPLUNK_START_ARGS: "--accept-license"
         SPLUNK_PASSWORD: $SPLUNK_PASSWORD
         SPLUNK_HEC_TOKEN: $SPLUNK_HEC_TOKEN
         SPLUNK_DEFAULTS_URL: $SPLUNK_DEFAULTS_URL
      ports:
         - 8000:8000
         - 8088:8088
      networks:
         - skynet

   # test:
   #    #image: ryans/test-service
   #    build:
   #       context: test-service/
   #    container_name: test
   #    environment:
   #       WAIT_FOR_IT_URL: $WAIT_FOR_IT_URL
   #    ports:
   #       - 5001:5001
   #    logging:
   #       driver: splunk
   #       options:
   #          splunk-url: $SPLUNK_URL
   #          splunk-token: $SPLUNK_HEC_TOKEN
   #          splunk-insecureskipverify: 'true'
   #    networks:
   #       - skynet