version: '3.5'

networks:
   skynet:

services:

   splunk:
      image: splunk/splunk
      container_name: splunk
      environment:
         SPLUNK_START_ARGS: "--accept-license"
         SPLUNK_PASSWORD: $SPLUNK_PASSWORD
         SPLUNK_HEC_TOKEN: $SPLUNK_HEC_TOKEN
         SPLUNK_DEFAULTS_URL: $SPLUNK_DEFAULTS_URL
      ports:
         - 8000:8000
         - 8088:8088
      networks:
         - skynet

   kafka:
      image: landoop/fast-data-dev:latest
      container_name: kafka
      environment:
         ADV_HOST: $ADV_HOST
      ports:
         - 2181:2181
         - 3030:3030
         - 8081-8083:8081-8083
         - 9581-9585:9581-9585
         - 9092:9092
      networks:
         - skynet

   test:
      build:
         context: test-service/
      container_name: test
      ports:
         - 5001:5001
      networks:
         - skynet

   otel:
      build:
         context: otel/
      container_name: otel
      restart: always
      environment:
         SPLUNK_HEC_URL: $SPLUNK_HEC_URL
         SPLUNK_HEC_TOKEN: $SPLUNK_HEC_TOKEN
      ports:
         - 4317:4317
      networks:
         - skynet