version: '3.5'

networks:
   skynet:

services:

   splunk:
      image: splunk/splunk
      environment:
         SPLUNK_START_ARGS: "--accept-license"
         SPLUNK_PASSWORD: $SPLUNK_PASSWORD
         SPLUNK_HEC_TOKEN: $SPLUNK_HEC_TOKEN
         SPLUNK_DEFAULTS_URL: $SPLUNK_DEFAULTS_URL
      ports:
         - 8000:8000
         - 8088:8088
      networks:
         - skynet

   logstash:
      build:
         context: logstash/
      container_name: logstash
      environment:
         LS_JAVA_OPTS: "-Xmx256m -Xms256m"
         SPLUNK_HEC_URL: $SPLUNK_HEC_URL
         SPLUNK_HEC_TOKEN: $SPLUNK_HEC_TOKEN
      ports:
         - 5000:5000
         - 5043:5043
         - 12201:12201/udp
      networks:
         - skynet

   test:
      #image: ryans/test-service
      build:
         context: test-service/
      container_name: test
      ports:
         - 5001:5001
      logging:
         driver: gelf
         options:
            gelf-address: $GELF_ADDRESS
            gelf-compression-type: gzip
      networks:
         - skynet