receivers:

  filelog:
    include: [ /var/log/*.txt ]

  prometheus:
    config:
      scrape_configs:
        - job_name: "test-metrics"
          scrape_interval: 10s
          static_configs:
            - targets: [ 'test:5001' ]

  # otlp:
  #   protocols:
  #     grpc:
  #     http:

exporters:

  # splunk_hec:
  #   token: "${SPLUNK_HEC_TOKEN}"
  #   endpoint: "http://splunk:8088/services/collector"
  #   source: "otel"
  #   sourcetype: "otel"
  #   insecure_skip_verify: true

  kafka:
    brokers:
      - "kafka:9093"
    protocol_version: 2.6.2
    topic: logs
    encoding: otlp_json

  kafka/2:
    brokers:
      - "kafka:9093"
    protocol_version: 2.6.2
    topic: metrics
    encoding: otlp_json

  kafka/3:
    brokers:
      - "kafka:9093"
    protocol_version: 2.6.2
    topic: traces
    encoding: otlp_proto

service:
  pipelines:
    logs:
      receivers: [filelog]
      exporters: [kafka]
    metrics:
      receivers: [prometheus]
      exporters: [kafka/2]
    # traces:
    #   receivers: [otlp]
    #   exporters: [kafka/3]
